name: Teste Workflow

on:
  push:
    branches: [ main, developer ]

# Definindo os jobs que 0 workflow executará
jobs:
  test_job:
    name: Executando o Job de Teste
    runs-on: self-hosted
    steps:
    - name: Step 1
      uses: actions/checkout@v2

    - name: Step 2
      run : echo "Este é o nosso primeiro jobsef-hosted"
